name: SLQNE Hockey Stats
version: "1.6.7"   # ← bump pour recharger le schéma
slug: slqne_hockey_stats
description: >
  Récupère et publie via MQTT les statistiques de la SLQNE (classements, joueurs, gardiens)
  à partir du site Spordle (ligue de hockey mineur Capitale-Nationale).
url: "https://github.com/Frazou1/slqne_hockey"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw

options:
  entity_prefix: "slqne"
  teams:
    - name: "Hayden Hockey"
      league_id: "bf27e08e-8d52-41be-a097-a6cf79f4466a"
      schedule_id: "183363"
    - name: "Loik Hockey"
      league_id: "13c38dd1-e464-4835-af5f-75be8561daf6"
      schedule_id: "183367"

  # 🧩 joueurs suivis (override possible par joueur si tu ajoutes league_id/schedule_id ici)
  players:
    - player_name: "Hayden Fraser"
      team_name: "Hayden Hockey"
    - player_name: "Loik Fraser"
      team_name: "Loik Hockey"

  update_interval: 7200  # toutes les 2 heures
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "monuser"
  mqtt_password: "monpassword"
  discovery_prefix: "homeassistant"

schema:
  entity_prefix: str?
  teams:
    - name: str
      league_id: str
      schedule_id: str
  players:
    - player_name: str
      team_name: str
      league_id: str?      # ← autorisé (override par joueur)
      schedule_id: str?    # ← autorisé (override par joueur)
  update_interval: int(30,86400)
  mqtt_host: str
  mqtt_port: int(1,65535)
  mqtt_username: str
  mqtt_password: str
  discovery_prefix: str

build:
  builder: docker
  file: Dockerfile
